project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  # UI (JSON)
  - source: /src/localize/lang/en.json
    translation: /src/localize/lang/%two_letters_code%.json
    type: json

  # Dokumentacja
  - source: /README.md
    translation: /docs/%two_letters_code%/README.md
  - source: /examples/**/*.md
    translation: /docs/%two_letters_code%/%original_path%/%original_file_name%
