// localize/localize.js
const DICTS = {
  en: {
    editor: {
      appearance: "Appearance & Style",
      card_title: "Flex Cells card configuration",
      columns_count: "Columns",
      text_size_global: "Text size (default)",
      card_padding: "Card padding",
      cell_padding_top: "Cell padding - top",
      cell_padding_right: "Cell padding - right",
      cell_padding_bottom: "Cell padding - bottom",
      cell_padding_left: "Cell padding - left",
      widths_label: "Column widths (px/%/rem/auto), e.g. \"80px, auto, 25%, 12rem\"",
      hide_cols_label: "Columns to hide below breakpoint (e.g. 1,4)",
      sort_cols_label: "Sort rows by columns (e.g. \"5,2,3\")",
      sort_desc_label: "Reverse sort",
      sort_hide_separators_label: "Hide separators when sorting is enabled",
      sort_hint_grouped: "If you add a separator it splits your rows into groups. Each group is sorted independently.",
      breakpoint: "Breakpoint (px)",
      overflow_x: "Horizontal scroll (overflow-x)",
      header_from_first: "Use first row as header",
      zebra: "Zebra stripes",
      zebra_skip_separators: "Skip separators in zebra pattern",
      row: "Row",
      header_suffix: " - header",
      tab_first: "Column 1",
      merge_all_columns: "Merge all columns",
      copy: "Copy configuration",
      paste: "Paste configuration",
      clipboard_empty: "Clipboard empty",
      align: "Alignment",
      unit_from_entity: "Use unit from entity",
      precision: "Precision",
      show_control: "Show control",
      press: "Press",
      entity_display_label: "Entity display",
      entity_display_option_value: "Entity/metadata value",
      entity_display_option_icon: "Entity icon",
      entity_display_option_icon_value: "Icon and value",
      background_color: "Background color",
      content_color: "Content color",
      text_color: "Text color",
      text_size: "Text size",
      text_transform: "Text transform",
      letter_spacing: "Letter spacing",
      icon_color: "Icon color",
      icon_size: "Icon size",
      add_row: "Add row",
      add_separator: "Add separator",
      custom_template: "Custom template (beta)",
      custom_template_hint: "Use any HTML plus the <fcc row=\"3\" col=\"2\" /> tag to insert a cell from the table.",
      delete_row: "Delete row",
      separator_title: "Separator",
      separator_appearance: "Separator appearance",
      separator_color: "Separator color",
      separator_background: "Background color",
      separator_color_picker: "Color picker",
      separator_style: "Line style",
      separator_style_solid: "Solid",
      separator_style_dashed: "Dashed",
      separator_style_dotted: "Dotted",
      separator_thickness: "Thickness (px)",
      separator_length: "Length / width",
      separator_align: "Alignment",
      separator_align_full: "Full width",
      separator_align_center: "Center",
      separator_align_left: "Left",
      separator_align_right: "Right",
      separator_opacity: "Opacity",
      separator_margin_top: "Margin top (px)",
      separator_margin_bottom: "Margin bottom (px)",
      separator_zero_hint: "If you set the separator thickness to zero it will be invisible but it still divides rows into groups that are used when sorting.",
      column: "Column",
      drag_to_reorder: "Drag to reorder",
      move_left: "Move left",
      move_right: "Move right",
      up: "Move up",
      down: "Move down",
      toggle: "Collapse/Expand",
      delete_column: "Delete column",
      cell_type: "Cell type",
      entity_label: "Entity",
      string_label: "Text",
      icon_label: "Icon",
      tap_action: "Tap action",
      hold_action: "Hold action",
      double_tap_action: "Double-tap action",
      advanced: "Tap & Hold Actions",
      actions_hint: "If any action is set, the default 'more-info' for an entity will be disabled.",
      scale_title: "Rescale",
      scale_in_min: "Input min",
      scale_in_max: "Input max",
      scale_out_min: "Output min",
      scale_out_max: "Output max",
      scale_hint: "Map a numeric value from one range to another (e.g., 0-255 → 0-100).",
      dynamic_title: "Dynamic Rules (cell): Color & Content Overrides",
      dynamic_row_title: "Dynamic Rules (row): Color & Row Hiding",
      dynamic_hint: "Evaluate rules from top to bottom, the last match wins.",
      datetime_format: "Date/Time format & Text override",
      available_tokens: "Available tokens: YYYY, YY, MM, M, DD, D, HH, H, hh, h, mm, m, ss, s, MMMM, [literals in brackets]",
      value: "Value"
    },
    placeholder: {
      entity: "Select entity",
      string: "Text to display",
      icon: "mdi:icon-name",
      datetime_format: "e.g. H:mm:ss, YYYY-MM-DD H:mm or [Custom text]",
      attribute_path: "Metadata path (e.g. a.b[0].c)"
    },
    dynamic: {
      operator: "Operator",
      add_rule: "Add rule",
      delete_rule: "Delete",
      op_between: "between",
      op_contains: "contains",
      op_not_contains: "does not contain",
      min: "Min",
      max: "Max",
      bg: "Background color",
      fg: "Content color",
      overwrite_label: "Overwrite content",
      overwrite_hide: "Hide",
      overwrite_text: "Overwrite with text",
      overwrite_icon: "Overwrite with icon",
      overwrite_entity_metadata: "Overwrite with entity/metadata",
      visibility_label: "Visibility",
      visibility_visible: "Visible",
      visibility_hidden: "Hidden",
      text: "Text",
    },
    align: {
      left: "left",
      center: "center",
      right: "right"
    },
    precision: {
      two: "two decimals",
      one: "one decimal",
      int: "integer"
    },
    style: {
      bold: "bold",
      italic: "italic",
      underline: "underline",
      strike: "strikethrough"
    },
    card: {
      no_rows: "No rows to display."
    }
  },

  pl: {
    editor: {
      appearance: "Wygląd i styl",
      card_title: "Konfiguracja karty Flex Cells",
      columns_count: "Liczba kolumn",
      text_size_global: "Rozmiar tekstu (domyślny)",
      card_padding: "Padding karty",
      cell_padding_top: "Padding komórki - góra",
      cell_padding_right: "Padding komórki - prawa",
      cell_padding_bottom: "Padding komórki - dół",
      cell_padding_left: "Padding komórki - lewa",
      widths_label: "Szerokości kolumn (px/%/rem/auto), np. \"80px, auto, 25%, 12rem\"",
      hide_cols_label: "Kolumny do ukrycia poniżej breakpointu (np. 1,4)",
      sort_cols_label: "Kolumny do sortowania wierszy (np. 5,2,3)",
      sort_desc_label: "Odwróć sortowanie",
      sort_hide_separators_label: "Ukryj separatory gdy sortowanie jest włączone",
      sort_hint_grouped: "Jeśli użyjesz separatora, podzieli on twoje wiersze na grupy. Każda grupa jest sortowana indywidualnie.",
      breakpoint: "Breakpoint (px)",
      overflow_x: "Poziomy scroll (overflow-x)",
      header_from_first: "Użyj pierwszego wiersza jako nagłówka",
      zebra: "Zebra stripes",
      zebra_skip_separators: "Nie uwzględniaj separatora",
      row: "Wiersz",
      header_suffix: " - nagłówek",
      tab_first: "Kolumna 1",
      merge_all_columns: "Scal wszystkie kolumny",
      copy: "Kopiuj konfigurację",
      paste: "Wklej konfigurację",
      clipboard_empty: "Schowek pusty",
      align: "Wyrównanie",
      unit_from_entity: "Jednostka z encji",
      precision: "Precyzja",
      show_control: "Pokaż kontrolkę",
      press: "Wciśnij",
      entity_display_label: "Wyświetlanie encji",
      entity_display_option_value: "Wartość encji/metadanych",
      entity_display_option_icon: "Ikona encji",
      entity_display_option_icon_value: "Ikona i wartość",
      background_color: "Kolor tła",
      content_color: "Kolor zawartości",
      text_color: "Tekst kolor",
      text_size: "Tekst rozmiar",
      text_transform: "Tekst transformacja",
      letter_spacing: "Odstępy między literami",
      icon_color: "Ikona kolor",
      icon_size: "Ikona rozmiar",
      add_row: "Dodaj wiersz",
      add_separator: "Dodaj separator",
      custom_template: "Własny szablon (beta)",
      custom_template_hint: "Użyj dowolnego HTML oraz tagu <fcc row=\"3\" col=\"2\" /> aby wstawić komorkę z tabeli.",
      delete_row: "Usuń wiersz",
      separator_title: "Separator",
      separator_appearance: "Wyglad separatora",
      separator_color: "Kolor separatora",
      separator_background: "Kolor tła separatora",
      separator_color_picker: "Wybierz kolor",
      separator_style: "Styl linii",
      separator_style_solid: "Ciągła",
      separator_style_dashed: "Przerywana",
      separator_style_dotted: "Kropkowana",
      separator_thickness: "Grubość (px)",
      separator_length: "Długość / szerokość",
      separator_align: "Wyrównanie",
      separator_align_full: "Pełna szerokość",
      separator_align_center: "Środek",
      separator_align_left: "Lewo",
      separator_align_right: "Prawo",
      separator_opacity: "Przezroczystość",
      separator_margin_top: "Margines górny (px)",
      separator_margin_bottom: "Margines dolny (px)",
      separator_zero_hint: "Jeśli ustawisz grubość separatora na zero, separator będzie niewidoczny, ale nadal podzieli wiersze na grupy brane pod uwagę przy sortowaniu.",
      column: "Kolumna",
      drag_to_reorder: "Przeciągnij, aby zmienić kolejność",
      move_left: "Przenieś w lewo",
      move_right: "Przenieś w prawo",
      up: "Przenieś w górę",
      down: "Przenieś w dół",
      toggle: "Zwiń/Rozwiń",
      delete_column: "Usuń kolumnę",
      cell_type: "Typ komórki",
      entity_label: "Encja",
      string_label: "Tekst",
      icon_label: "Ikona",
      tap_action: "Akcja po kliknięciu",
      hold_action: "Akcja po przytrzymaniu",
      double_tap_action: "Akcja po dwukliku",
      advanced: "Akcje dotknięcia i przytrzymania",
      actions_hint: "Jeśli ustawisz jakąkolwiek akcję, domyślne 'more-info' dla encji zostanie wyłączone.",
      scale_title: "Przeskalowanie",
      scale_in_min: "Wejście min",
      scale_in_max: "Wejście max",
      scale_out_min: "Wyjście min",
      scale_out_max: "Wyjście max",
      scale_hint: "Mapuj wartość z jednego zakresu na inny (np. 0-255 → 0-100).",
      dynamic_title: "Reguły dynamiczne (komórka): kolor i nadpisywanie treści",
      dynamic_row_title: "Reguły dynamiczne (wiersz): kolor i ukrywanie wiersza",
      dynamic_hint: "Reguły sprawdzane są od góry do dołu, ostatnia dopasowana wygrywa.",
      datetime_format: "Format daty/czasu i nadpisanie tekstu",
      available_tokens: "Dostępne tokeny: YYYY, YY, MM, M, DD, D, HH, H, hh, h, mm, m, ss, s, MMMM, [literały w nawiasach]",
      value: "Wartość"
    },
    placeholder: {
      entity: "Wybierz encję",
      string: "Tekst do wyświetlenia",
      icon: "mdi:nazwa-ikony",
      datetime_format: "np. H:mm:ss, YYYY-MM-DD H:mm lub [dowolny tekst]",
      attribute_path: "Ścieżka metadanych (np. a.b[0].c)"
    },
    dynamic: {
      operator: "Operator",
      add_rule: "Dodaj regułę",
      delete_rule: "Usuń",
      op_between: "pomiędzy",
      op_contains: "zawiera",
      op_not_contains: "nie zawiera",
      min: "Min",
      max: "Max",
      bg: "Kolor tła",
      fg: "Kolor zawartości",
      overwrite_label: "Nadpisz zawartość",
      overwrite_hide: "Ukryj",
      overwrite_text: "Nadpisz tekstem",
      overwrite_icon: "Nadpisz ikoną",
      overwrite_entity_metadata: "Nadpisz encją/metadanymi",
      visibility_label: "Widoczność",
      visibility_visible: "Widoczny",
      visibility_hidden: "Ukryty",
      text: "Tekst",
    },
    align: {
      left: "lewo",
      center: "środek",
      right: "prawo"
    },
    precision: {
      two: "dwa miejsca",
      one: "jedno miejsce",
      int: "liczba całkowita"
    },
    style: {
      bold: "pogrubienie",
      italic: "kursywa",
      underline: "podkreślenie",
      strike: "przekreślenie"
    },
    card: {
      no_rows: "Brak wierszy do wyświetlenia."
    }
  },

  de: {
    editor: {
      appearance: "Aussehen & Stil",
      card_title: "Flex Cells card konfigurieren",
      columns_count: "Spalten",
      text_size_global: "Textgröße (Standard)",
      card_padding: "Kartenabstand",
      cell_padding_top: "Zellenabstand - oben",
      cell_padding_right: "Zellenabstand - rechts",
      cell_padding_bottom: "Zellenabstand - unten",
      cell_padding_left: "Zellenabstand - links",
      widths_label: "Spaltenbreite (px/%/rem/auto), z. B. \"80px, auto, 25%, 12rem\"",
      hide_cols_label: "Spalten, die unterhalb des Breakpoints ausgeblendet werden (z. B. 1,4)",
      sort_cols_label: "Spalten zum Sortieren der Zeilen (z. B. 5,2,3)",
      sort_desc_label: "Sortierung umkehren",
      sort_hide_separators_label: "Separatoren beim Sortieren ausblenden",
      sort_hint_grouped: "Wenn du einen Separator einfügst, teilt er deine Zeilen in Gruppen. Jede Gruppe wird separat sortiert.",
      breakpoint: "Breakpoint (px)",
      overflow_x: "Horizontaler Scroll (overflow-x)",
      header_from_first: "Erste Zeile als Kopfzeile verwenden",
      zebra: "Zebrastreifen",
      zebra_skip_separators: "Separatoren auslassen",
      row: "Zeile",
      header_suffix: " - Kopfzeile",
      tab_first: "Spalte 1",
      merge_all_columns: "Alle Spalten zusammenfuehren",
      copy: "Konfiguration kopieren",
      paste: "Konfiguration einfügen",
      clipboard_empty: "Zwischenablage leer",
      align: "Ausrichtung",
      unit_from_entity: "Einheit der Entität verwenden",
      precision: "Genauigkeit",
      show_control: "Steuerelement anzeigen",
      press: "Drücken",
      entity_display_label: "Entitaetsdarstellung",
      entity_display_option_value: "Entitaets-/Metadatenwert",
      entity_display_option_icon: "Entitaetssymbol",
      entity_display_option_icon_value: "Symbol und Wert",
      background_color: "Hintergrundfarbe",
      content_color: "Inhaltsfarbe",
      text_color: "Textfarbe",
      text_size: "Textgröße",
      text_transform: "Textumwandlung",
      letter_spacing: "Buchstabenabstand",
      icon_color: "Iconfarbe",
      icon_size: "Icongröße",
      add_row: "Zeile hinzufügen",
      add_separator: "Separator hinzufuegen",
      custom_template: "Eigenes Template (Beta)",
      custom_template_hint: "Nutze beliebiges HTML und den Tag <fcc row=\"3\" col=\"2\" /> um eine Tabellenzelle einzufuegen.",
      delete_row: "Zeile löschen",
      separator_title: "Separator",
      separator_appearance: "Separator Darstellung",
      separator_color: "Separatorfarbe",
      separator_background: "Separator-Hintergrundfarbe",
      separator_color_picker: "Farbauswahl",
      separator_style: "Linienstil",
      separator_style_solid: "Durchgezogen",
      separator_style_dashed: "Gestrichelt",
      separator_style_dotted: "Gepunktet",
      separator_thickness: "Linienstaerke (px)",
      separator_length: "Laenge / Breite",
      separator_align: "Ausrichtung",
      separator_align_full: "Volle Breite",
      separator_align_center: "Zentriert",
      separator_align_left: "Links",
      separator_align_right: "Rechts",
      separator_opacity: "Deckkraft",
      separator_margin_top: "Oberer Abstand (px)",
      separator_margin_bottom: "Unterer Abstand (px)",
      separator_zero_hint: "Wenn du die Dicke auf Null setzt, bleibt der Separator unsichtbar, trennt aber weiterhin Zeilengruppen, die beim Sortieren berücksichtigt werden.",
      column: "Spalte",
      drag_to_reorder: "Zum Umordnen ziehen",
      move_left: "nach links schieben",
      move_right: "nach rechts schieben",
      up: "Nach oben",
      down: "Nach unten",
      toggle: "Ein-/ausklappen",
      delete_column: "Spalte löschen",
      cell_type: "Zellentyp",
      entity_label: "Entität",
      string_label: "Text",
      icon_label: "Icon",
      tap_action: "Tippen-Aktion",
      hold_action: "Aktion bei Halten",
      double_tap_action: "Doppeltippen-Aktion",
      advanced: "Tippen & Halten Aktionen",
      actions_hint: "Wenn eine Aktion gesetzt ist, wird das Standard-\"more-info\" für die Entität deaktiviert.",
      scale_title: "Skalieren",
      scale_in_min: "Eingabe min",
      scale_in_max: "Eingabe max",
      scale_out_min: "Ausgabe min",
      scale_out_max: "Ausgabe max",
      scale_hint: "Numerischen Wert von einem Bereich in einen anderen abbilden (z. B. 0-255 → 0-100).",
      dynamic_title: "Dynamische Regeln (Zelle): Farb- & Inhalts-Übersteuerung",
      dynamic_row_title: "Dynamische Regeln (Zeile): Farben und Zeilenausblenden",
      dynamic_hint: "Regeln von oben nach unten prüfen, die letzte Übereinstimmung gewinnt.",
      datetime_format: "Datums-/Zeitformat & Textüberschreibung",
      available_tokens: "Verfügbare Tokens: YYYY, YY, MM, M, DD, D, HH, H, hh, h, mm, m, ss, s, MMMM, [Literale in Klammern]",
      value: "Wert"
    },
    placeholder: {
      entity: "Entität auswählen",
      string: "Anzuzeigender Text",
      icon: "mdi:icon-name",
      datetime_format: "z. B. H:mm:ss, YYYY-MM-DD H:mm oder [eigener Text]",
      attribute_path: "Metadatenpfad (z. B. a.b[0].c)"
    },
    dynamic: {
      operator: "Operator",
      add_rule: "Regel hinzufügen",
      delete_rule: "Löschen",
      op_between: "zwischen",
      op_contains: "enthält",
      op_not_contains: "enthält nicht",
      min: "Min",
      max: "Max",
      bg: "Hintergrundfarbe",
      fg: "Inhaltsfarbe",
      overwrite_label: "Inhalt überschreiben",
      overwrite_hide: "Ausblenden",
      overwrite_text: "Mit Text überschreiben",
      overwrite_icon: "Mit Icon überschreiben",
      overwrite_entity_metadata: "Mit Entitaet/Metadaten ueberschreiben",
      visibility_label: "Sichtbarkeit",
      visibility_visible: "Sichtbar",
      visibility_hidden: "Versteckt",
      text: "Text",
    },
    align: {
      left: "links",
      center: "zentriert",
      right: "rechts"
    },
    precision: {
      two: "zwei Dezimalstellen",
      one: "eine Dezimalstelle",
      int: "Ganzzahl"
    },
    style: {
      bold: "fett",
      italic: "kursiv",
      underline: "unterstrichen",
      strike: "durchgestrichen"
    },
    card: {
      no_rows: "Keine Zeilen zum Anzeigen."
    }
  }
};

export function t(hass, key) {
  const langCode = (hass?.locale?.language || "en").toLowerCase();
  const lang = langCode.startsWith("pl")
    ? "pl"
    : langCode.startsWith("de")
      ? "de"
      : "en";
  const parts = key.split(".");
  let node = DICTS[lang];
  for (const p of parts) {
    node = node?.[p];
    if (node === undefined) break;
  }
  if (node !== undefined) return node;

  // fallback to EN
  node = DICTS.en;
  for (const p of parts) {
    node = node?.[p];
    if (node === undefined) break;
  }
  return node ?? key;
}
