alias: Spotify volume - slider to player
description: ""
triggers:
  - entity_id: input_number.spotify_volume_slider
    trigger: state
actions:
  - wait_for_trigger:
      - entity_id: input_number.spotify_volume_slider
        trigger: state
    timeout:
      milliseconds: 250
    continue_on_timeout: true
  - condition: template
    value_template: |
      {{ states('input_number.spotify_volume_slider')|int
         != states('input_number.spotify_volume_state')|int }}
  - target:
      entity_id: media_player.spotify_lukasz
    data:
      volume_level: >
        {{ (states('input_number.spotify_volume_slider')|int / 100) | round(2)
        }}
    action: media_player.volume_set
  - target:
      entity_id: input_number.spotify_volume_state
    data:
      value: "{{ states('input_number.spotify_volume_slider')|int }}"
    action: input_number.set_value
mode: restart
