name: Build & Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Jeśli workflow wywołał *release published* → tylko dołącz asset
      - name: Upload asset to existing release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/flex-cells-card.js

      # Jeśli workflow wywołał *push tag* → utwórz release i dołącz asset
      - name: Create release from tag and upload asset
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/flex-cells-card.js
